
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.1
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.1",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  passwordHash: 'passwordHash',
  role: 'role',
  staffType: 'staffType',
  isActive: 'isActive',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  lastLoginAt: 'lastLoginAt',
  tokenVersion: 'tokenVersion',
  phone: 'phone',
  avatar: 'avatar',
  customRoleId: 'customRoleId',
  resetPasswordToken: 'resetPasswordToken',
  resetPasswordExpiry: 'resetPasswordExpiry',
  emailVerified: 'emailVerified',
  emailVerificationToken: 'emailVerificationToken',
  emailVerificationExpiry: 'emailVerificationExpiry',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  permissions: 'permissions',
  isDefault: 'isDefault',
  isProtected: 'isProtected',
  isActive: 'isActive',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PermissionScalarFieldEnum = {
  id: 'id',
  module: 'module',
  action: 'action',
  description: 'description',
  createdAt: 'createdAt'
};

exports.Prisma.ApplicationScalarFieldEnum = {
  id: 'id',
  applicationNumber: 'applicationNumber',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  clientId: 'clientId',
  assignedToId: 'assignedToId',
  approvedById: 'approvedById',
  companyName: 'companyName',
  licenseType: 'licenseType',
  visaType: 'visaType',
  bankName: 'bankName',
  serviceDetails: 'serviceDetails',
  notes: 'notes',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ClientScalarFieldEnum = {
  id: 'id',
  clientNumber: 'clientNumber',
  name: 'name',
  email: 'email',
  phone: 'phone',
  company: 'company',
  companyType: 'companyType',
  designation: 'designation',
  natureOfBusiness: 'natureOfBusiness',
  country: 'country',
  city: 'city',
  howDidYouHear: 'howDidYouHear',
  userId: 'userId',
  groupId: 'groupId',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  servicePackageId: 'servicePackageId',
  profileCompletionStatus: 'profileCompletionStatus',
  profileCompletedAt: 'profileCompletedAt'
};

exports.Prisma.ClientCollaboratorScalarFieldEnum = {
  id: 'id',
  clientId: 'clientId',
  collaboratorUserId: 'collaboratorUserId',
  inviteEmail: 'inviteEmail',
  inviteToken: 'inviteToken',
  status: 'status',
  invitedAt: 'invitedAt',
  acceptedAt: 'acceptedAt',
  expiresAt: 'expiresAt',
  revokedAt: 'revokedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DocumentScalarFieldEnum = {
  id: 'id',
  filename: 'filename',
  originalName: 'originalName',
  path: 'path',
  size: 'size',
  mimeType: 'mimeType',
  status: 'status',
  reviewNotes: 'reviewNotes',
  name: 'name',
  description: 'description',
  uploadedById: 'uploadedById',
  reviewedById: 'reviewedById',
  applicationId: 'applicationId',
  leadId: 'leadId',
  clientId: 'clientId',
  profileRequirementId: 'profileRequirementId',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ServiceCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  sortOrder: 'sortOrder',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BusinessServiceScalarFieldEnum = {
  id: 'id',
  categoryId: 'categoryId',
  name: 'name',
  slug: 'slug',
  description: 'description',
  sortOrder: 'sortOrder',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ServicePackageScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  basePriceUsd: 'basePriceUsd',
  basePriceSar: 'basePriceSar',
  isActive: 'isActive',
  isFeatured: 'isFeatured',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PackageServiceScalarFieldEnum = {
  id: 'id',
  packageId: 'packageId',
  serviceId: 'serviceId'
};

exports.Prisma.AdditionalServiceScalarFieldEnum = {
  id: 'id',
  serviceId: 'serviceId',
  name: 'name',
  slug: 'slug',
  description: 'description',
  priceUsd: 'priceUsd',
  priceSar: 'priceSar',
  isActive: 'isActive',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormFieldScalarFieldEnum = {
  id: 'id',
  label: 'label',
  type: 'type',
  options: 'options',
  helpText: 'helpText',
  placeholder: 'placeholder',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  isActive: 'isActive',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  areaOfInterest: 'areaOfInterest'
};

exports.Prisma.FormTemplateFieldScalarFieldEnum = {
  id: 'id',
  templateId: 'templateId',
  fieldId: 'fieldId',
  sortOrder: 'sortOrder',
  isRequired: 'isRequired',
  labelOverride: 'labelOverride',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormTemplateServiceScalarFieldEnum = {
  id: 'id',
  templateId: 'templateId',
  serviceId: 'serviceId',
  createdAt: 'createdAt'
};

exports.Prisma.ApplicationWizardScalarFieldEnum = {
  id: 'id',
  name: 'name',
  areaOfInterest: 'areaOfInterest',
  isActive: 'isActive',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ApplicationWizardStepScalarFieldEnum = {
  id: 'id',
  wizardId: 'wizardId',
  formTemplateId: 'formTemplateId',
  sortOrder: 'sortOrder',
  paymentRequired: 'paymentRequired',
  approvalRequired: 'approvalRequired',
  adminUseOnly: 'adminUseOnly',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WizardApplicationScalarFieldEnum = {
  id: 'id',
  applicationNumber: 'applicationNumber',
  clientId: 'clientId',
  wizardId: 'wizardId',
  areaOfInterest: 'areaOfInterest',
  status: 'status',
  currentStepIndex: 'currentStepIndex',
  adminNotes: 'adminNotes',
  submittedAt: 'submittedAt',
  assignedToId: 'assignedToId',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WizardApplicationAnswerScalarFieldEnum = {
  id: 'id',
  applicationId: 'applicationId',
  wizardStepId: 'wizardStepId',
  fieldId: 'fieldId',
  value: 'value',
  fileUrl: 'fileUrl',
  updatedById: 'updatedById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WizardApplicationStepReviewScalarFieldEnum = {
  id: 'id',
  applicationId: 'applicationId',
  wizardStepId: 'wizardStepId',
  status: 'status',
  rejectionNote: 'rejectionNote',
  reviewedById: 'reviewedById',
  reviewedAt: 'reviewedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ApplicationWizardServiceScalarFieldEnum = {
  id: 'id',
  wizardId: 'wizardId',
  serviceId: 'serviceId',
  createdAt: 'createdAt'
};

exports.Prisma.PaymentPhaseTemplateScalarFieldEnum = {
  id: 'id',
  phaseNumber: 'phaseNumber',
  name: 'name',
  description: 'description',
  percentage: 'percentage',
  sortOrder: 'sortOrder',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProfileDocumentRequirementScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  description: 'description',
  inputType: 'inputType',
  isRequired: 'isRequired',
  sortOrder: 'sortOrder',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ClientProfileDocumentScalarFieldEnum = {
  id: 'id',
  clientId: 'clientId',
  requirementId: 'requirementId',
  documentId: 'documentId',
  status: 'status',
  notes: 'notes',
  submittedAt: 'submittedAt',
  reviewedAt: 'reviewedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaskScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  status: 'status',
  priority: 'priority',
  assignedToId: 'assignedToId',
  applicationId: 'applicationId',
  dueDate: 'dueDate',
  completedAt: 'completedAt',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ExpenseScalarFieldEnum = {
  id: 'id',
  description: 'description',
  amount: 'amount',
  category: 'category',
  vendor: 'vendor',
  expenseDate: 'expenseDate',
  notes: 'notes',
  approvedById: 'approvedById',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  invoiceNumber: 'invoiceNumber',
  clientId: 'clientId',
  amount: 'amount',
  status: 'status',
  dueDate: 'dueDate',
  paidAt: 'paidAt',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  amount: 'amount',
  method: 'method',
  reference: 'reference',
  clientId: 'clientId',
  invoiceId: 'invoiceId',
  status: 'status',
  gateway: 'gateway',
  edfaPayOrderId: 'edfaPayOrderId',
  edfaPayTransactionId: 'edfaPayTransactionId',
  edfaPayResponse: 'edfaPayResponse',
  failureReason: 'failureReason',
  paymentDate: 'paymentDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentIntentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  invoiceId: 'invoiceId',
  clientId: 'clientId',
  userId: 'userId',
  amount: 'amount',
  gateway: 'gateway',
  createdAt: 'createdAt'
};

exports.Prisma.PaymentGatewaySettingsScalarFieldEnum = {
  id: 'id',
  merchantId: 'merchantId',
  password: 'password',
  apiKey: 'apiKey',
  environment: 'environment',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LeadScalarFieldEnum = {
  id: 'id',
  leadNumber: 'leadNumber',
  fullName: 'fullName',
  email: 'email',
  phone: 'phone',
  normalizedPhone: 'normalizedPhone',
  companyName: 'companyName',
  companyType: 'companyType',
  natureOfBusiness: 'natureOfBusiness',
  designation: 'designation',
  country: 'country',
  city: 'city',
  howDidYouHear: 'howDidYouHear',
  businessTypes: 'businessTypes',
  statusId: 'statusId',
  source: 'source',
  notes: 'notes',
  assignedToId: 'assignedToId',
  createdById: 'createdById',
  clientId: 'clientId',
  duplicateGroupId: 'duplicateGroupId',
  isDuplicate: 'isDuplicate',
  duplicateCount: 'duplicateCount',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LeadStatusScalarFieldEnum = {
  id: 'id',
  name: 'name',
  color: 'color',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LeadNoteScalarFieldEnum = {
  id: 'id',
  title: 'title',
  body: 'body',
  leadId: 'leadId',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LeadFollowUpScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  scheduledAt: 'scheduledAt',
  leadId: 'leadId',
  createdById: 'createdById',
  reminderSentAt: 'reminderSentAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MessageScalarFieldEnum = {
  id: 'id',
  applicationId: 'applicationId',
  senderId: 'senderId',
  content: 'content',
  status: 'status',
  isRead: 'isRead',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SupportMessageScalarFieldEnum = {
  id: 'id',
  visitorId: 'visitorId',
  content: 'content',
  visitorName: 'visitorName',
  visitorEmail: 'visitorEmail',
  isFromVisitor: 'isFromVisitor',
  status: 'status',
  staffId: 'staffId',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  isBot: 'isBot'
};

exports.Prisma.SupportConversationScalarFieldEnum = {
  id: 'id',
  visitorId: 'visitorId',
  status: 'status',
  channel: 'channel',
  visitorName: 'visitorName',
  visitorEmail: 'visitorEmail',
  handedOffAt: 'handedOffAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastMessageAt: 'lastMessageAt'
};

exports.Prisma.ChatbotSettingsScalarFieldEnum = {
  id: 'id',
  enabled: 'enabled',
  enabledWebsiteChat: 'enabledWebsiteChat',
  enabledWhatsApp: 'enabledWhatsApp',
  enabledEmail: 'enabledEmail',
  botName: 'botName',
  ollamaApiKey: 'ollamaApiKey',
  ollamaHost: 'ollamaHost',
  ollamaModel: 'ollamaModel',
  temperature: 'temperature',
  systemPrompt: 'systemPrompt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ClientGroupScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  color: 'color',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  message: 'message',
  type: 'type',
  isRead: 'isRead',
  isPinned: 'isPinned',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  entityType: 'entityType',
  entityId: 'entityId',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  entityId: 'entityId',
  entityName: 'entityName',
  action: 'action',
  userId: 'userId',
  oldValues: 'oldValues',
  newValues: 'newValues',
  changes: 'changes',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt'
};

exports.Prisma.PageAccessLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  path: 'path',
  pageTitle: 'pageTitle',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  referer: 'referer',
  createdAt: 'createdAt'
};

exports.Prisma.NotificationEventSettingScalarFieldEnum = {
  id: 'id',
  eventType: 'eventType',
  sendEmail: 'sendEmail',
  sendInApp: 'sendInApp',
  sendPush: 'sendPush',
  recipients: 'recipients',
  scheduleHour: 'scheduleHour',
  scheduleMinute: 'scheduleMinute',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificationPreferenceScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  eventType: 'eventType',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificationSettingsScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  reminderMinutesBefore: 'reminderMinutesBefore',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PushSubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  endpoint: 'endpoint',
  p256dh: 'p256dh',
  auth: 'auth',
  userAgent: 'userAgent',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EmailSettingsScalarFieldEnum = {
  id: 'id',
  mailDriver: 'mailDriver',
  host: 'host',
  port: 'port',
  username: 'username',
  password: 'password',
  encryption: 'encryption',
  fromAddress: 'fromAddress',
  fromName: 'fromName',
  tlsServername: 'tlsServername',
  allowBusinessEmailConfig: 'allowBusinessEmailConfig',
  enableNewBusinessEmail: 'enableNewBusinessEmail',
  enableNewSubscriptionEmail: 'enableNewSubscriptionEmail',
  enableWelcomeEmail: 'enableWelcomeEmail',
  welcomeEmailSubject: 'welcomeEmailSubject',
  welcomeEmailBody: 'welcomeEmailBody',
  contactEmail: 'contactEmail',
  contactPhone: 'contactPhone',
  businessConsultationRecipients: 'businessConsultationRecipients',
  staffWhatsAppNumbers: 'staffWhatsAppNumbers',
  enableWhatsAppNotifications: 'enableWhatsAppNotifications',
  whatsappAccessToken: 'whatsappAccessToken',
  whatsappApiVersion: 'whatsappApiVersion',
  whatsappPhoneNumberId: 'whatsappPhoneNumberId',
  whatsappDocumentUrl: 'whatsappDocumentUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GeneralSettingsScalarFieldEnum = {
  id: 'id',
  clientEmailNotifications: 'clientEmailNotifications',
  clientWhatsAppNotifications: 'clientWhatsAppNotifications',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.UserRole = exports.$Enums.UserRole = {
  CLIENT: 'CLIENT',
  STAFF: 'STAFF',
  ADMIN: 'ADMIN',
  COLLABORATOR: 'COLLABORATOR'
};

exports.StaffType = exports.$Enums.StaffType = {
  ADMIN: 'ADMIN',
  CASE_MANAGER: 'CASE_MANAGER',
  SALES: 'SALES',
  ACCOUNTANT: 'ACCOUNTANT'
};

exports.ApplicationStatus = exports.$Enums.ApplicationStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED'
};

exports.ProfileCompletionStatus = exports.$Enums.ProfileCompletionStatus = {
  INCOMPLETE: 'INCOMPLETE',
  PENDING_REVIEW: 'PENDING_REVIEW',
  COMPLETE: 'COMPLETE'
};

exports.CollaborationInviteStatus = exports.$Enums.CollaborationInviteStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED'
};

exports.DocumentStatus = exports.$Enums.DocumentStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

exports.FormFieldType = exports.$Enums.FormFieldType = {
  TEXT: 'TEXT',
  TEXTAREA: 'TEXTAREA',
  NUMBER: 'NUMBER',
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
  DATE: 'DATE',
  SELECT: 'SELECT',
  CHECKBOX: 'CHECKBOX',
  RADIO: 'RADIO',
  FILE: 'FILE',
  INSTRUCTION: 'INSTRUCTION'
};

exports.AreaOfInterest = exports.$Enums.AreaOfInterest = {
  CR: 'CR',
  PR: 'PR',
  GR: 'GR'
};

exports.WizardApplicationStatus = exports.$Enums.WizardApplicationStatus = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  HARD_COPY_REQUIRED: 'HARD_COPY_REQUIRED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED'
};

exports.WizardStepApprovalStatus = exports.$Enums.WizardStepApprovalStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

exports.ProfileRequirementType = exports.$Enums.ProfileRequirementType = {
  DOCUMENT: 'DOCUMENT',
  CONTACT_FIELD: 'CONTACT_FIELD'
};

exports.ProfileDocumentStatus = exports.$Enums.ProfileDocumentStatus = {
  MISSING: 'MISSING',
  UPLOADED: 'UPLOADED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

exports.TaskStatus = exports.$Enums.TaskStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  OVERDUE: 'OVERDUE'
};

exports.TaskPriority = exports.$Enums.TaskPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

exports.ExpenseCategory = exports.$Enums.ExpenseCategory = {
  OFFICE_SUPPLIES: 'OFFICE_SUPPLIES',
  TRAVEL: 'TRAVEL',
  MEALS: 'MEALS',
  SOFTWARE: 'SOFTWARE',
  MARKETING: 'MARKETING',
  UTILITIES: 'UTILITIES',
  RENT: 'RENT',
  OTHER: 'OTHER'
};

exports.InvoiceStatus = exports.$Enums.InvoiceStatus = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  CASH: 'CASH',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CREDIT_CARD: 'CREDIT_CARD',
  CHECK: 'CHECK',
  OTHER: 'OTHER'
};

exports.LeadStatusType = exports.$Enums.LeadStatusType = {
  OPEN: 'OPEN',
  WON: 'WON',
  LOST: 'LOST',
  OTHER: 'OTHER'
};

exports.Prisma.ModelName = {
  User: 'User',
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken',
  Role: 'Role',
  Permission: 'Permission',
  Application: 'Application',
  Client: 'Client',
  ClientCollaborator: 'ClientCollaborator',
  Document: 'Document',
  ServiceCategory: 'ServiceCategory',
  BusinessService: 'BusinessService',
  ServicePackage: 'ServicePackage',
  PackageService: 'PackageService',
  AdditionalService: 'AdditionalService',
  FormField: 'FormField',
  FormTemplate: 'FormTemplate',
  FormTemplateField: 'FormTemplateField',
  FormTemplateService: 'FormTemplateService',
  ApplicationWizard: 'ApplicationWizard',
  ApplicationWizardStep: 'ApplicationWizardStep',
  WizardApplication: 'WizardApplication',
  WizardApplicationAnswer: 'WizardApplicationAnswer',
  WizardApplicationStepReview: 'WizardApplicationStepReview',
  ApplicationWizardService: 'ApplicationWizardService',
  PaymentPhaseTemplate: 'PaymentPhaseTemplate',
  ProfileDocumentRequirement: 'ProfileDocumentRequirement',
  ClientProfileDocument: 'ClientProfileDocument',
  Task: 'Task',
  Expense: 'Expense',
  Invoice: 'Invoice',
  Payment: 'Payment',
  PaymentIntent: 'PaymentIntent',
  PaymentGatewaySettings: 'PaymentGatewaySettings',
  Lead: 'Lead',
  LeadStatus: 'LeadStatus',
  LeadNote: 'LeadNote',
  LeadFollowUp: 'LeadFollowUp',
  Message: 'Message',
  SupportMessage: 'SupportMessage',
  SupportConversation: 'SupportConversation',
  ChatbotSettings: 'ChatbotSettings',
  ClientGroup: 'ClientGroup',
  Notification: 'Notification',
  AuditLog: 'AuditLog',
  PageAccessLog: 'PageAccessLog',
  NotificationEventSetting: 'NotificationEventSetting',
  NotificationPreference: 'NotificationPreference',
  NotificationSettings: 'NotificationSettings',
  PushSubscription: 'PushSubscription',
  EmailSettings: 'EmailSettings',
  GeneralSettings: 'GeneralSettings'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
